version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory-database
    volumes:
      - ./db/schema/:/docker-entrypoint-initdb.d/schema/
      - ./db/data/:/docker-entrypoint-initdb.d/data/
    ports:
      - "5432:5432"
